name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          echo "$UNITY_LICENSE" > unity.ulf
          mkdir -p ~/.local/share/unity3d/Unity/
          mv unity.ulf ~/.local/share/unity3d/Unity/Unity_lic.ulf

      - name: Run Unity Build
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: "2022.3.53f1"
          targetPlatform: "StandaloneWindows64"
          buildsPath: Builds/

