name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          mkdir -p ~/.local/share/unity3d/Unity/
          echo "$UNITY_LICENSE" | tr -d '\n' | base64 --decode > ~/.local/share/unity3d/Unity/Unity_lic.ulf

      - name: Validate License File
        run: |
          if [ -f ~/.local/share/unity3d/Unity/Unity_lic.ulf ]; then
            echo "License file successfully created."
          else
            echo "License file creation failed!"
            exit 1
          fi

      - name: Run Unity Build
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: "2022.3.53f1"
          targetPlatform: "StandaloneWindows64"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "GameBuild"
          path: "Builds"
