name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Use the Unity License
      - name: Set up Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          echo "$UNITY_LICENSE" > unity.ulf
          mkdir -p ~/.local/share/unity3d/Unity/
          mv unity.ulf ~/.local/share/unity3d/Unity/Unity_lic.ulf

      # Build Unity Project
      - name: Run Unity Build
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: "2022.3.53f1"
          targetPlatform: "StandaloneWindows64"

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: GameBuild
          path: Builds/

      # Upload Build Logs
      - name: Upload Build Logs
        uses: actions/upload-artifact@v3
        with:
          name: BuildLogs
          path: BuildLogs/

