name: Validate Unity License

on:
  push:
    branches:
      - main

jobs:
  validate-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          mkdir -p ~/.local/share/unity3d/Unity/
          echo "$UNITY_LICENSE" | tr -d '\n' | base64 --decode > ~/.local/share/unity3d/Unity/Unity_lic.ulf

      - name: Install Unity and Validate License
        uses: game-ci/unity-builder@2
        with:
          unityVersion: "2022.3.53f1"
          targetPlatform:  "StandaloneWindows64"

      - name: Validate Unity License
        run: |
          if unity-editor --version; then
            echo "Unity license validated successfully."
          else
            echo "Error: Unity license validation failed."
            exit 1
          fi
