name: Validate Unity License

on:
  push:
    branches:
      - main

jobs:
  validate-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
         mkdir -p ~/.local/share/unity3d/Unity/
         echo "$UNITY_LICENSE" | tr -d '\n' | base64 --decode > ~/.local/share/unity3d/Unity/Unity_lic.ulf
         if [ $? -ne 0 ]; then
         echo "Failed to decode UNITY_LICENSE. Please ensure it is a valid base64 string."
         exit 1
         fi
         echo "License file successfully created."


      - name: Install Unity and Validate License
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: "2022.3.53f1"
          targetPlatform:  "StandaloneWindows64"

      - name: Validate Unity License
        run: |
          if unity-editor --version; then
            echo "Unity license validated successfully."
          else
            echo "Error: Unity license validation failed."
            exit 1
          fi
